version: "3.8"
services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - ./src/.env
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8000:8000

  api:
    build: ./src
    env_file:
      - ./src/.env
    depends_on:
      - db
    ports:
      - ${FAST_API_PORT}:8080