version: "3.8"
services:
  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
  api:
    build: ./src
    image: api:${API_VERSION}
    restart: on-failure
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - ${API_PORT}:8080